services:
  frontend:
    build:
      context: ./todoapp-fe
    ports:
      - "3000:3000"
    volumes:
      - ./todoapp-fe/src:/app/src
    environment:
      NODE_ENV: dev
      VITE_API_URL: http://localhost:8080
      
  backend:
    build:
      context: ./todoapp-be
    ports:
      - "8080:3000"
    volumes:
      - ./todoapp-be/src:/app/src
    environment:
      NODE_ENV: dev
      PORT: 3000
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      
    depends_on:
      - database

  database:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres_data:

